// @ts-check

/**
 * Sidebar configuration for the Physical AI & Humanoid Robotics book.
 * Uses autogenerated sidebar that discovers docs from the filesystem.
 * Categories are defined in _category_.json files within each directory.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  bookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
